// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yknvvzchbibtzopbggob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbnZ2emNoYmlidHpvcGJnZ29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxNzU2ODEsImV4cCI6MjA5NTc1MTY4MX0._xCHf_cTDpEh6LFQA8iOYAGGJIoeTPPPANrrmSIRXtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});